server:
    port: ${SERVER_PORT}
    compression:
        enabled: true
        mime-types: application/json
        min-response-size: 1024

spring:
    application:
        name: candido
    sql:
        init:
            mode: never
    main:
        allow-bean-definition-overriding: true
    mvc:
        view:
            prefix: /templates
            suffix: .html
        pathpattern:
            matching-strategy: ANT_PATH_MATCHER
    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 50
            minimum-idle: 10
            idle-timeout: 60000
            max-lifetime: 1800000
            connection-timeout: 5000
            leak-detection-threshold: 60000
    flyway:
        enabled: true
        locations: classpath:db/migration,classpath:db/dummy-data
        create-schemas: true
        clean-disabled: false
        baseline-on-migrate: true
        schemas: ${DB_NAME}
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                generate_statistics: true

                # PLEASE, DO NOT CHANGE THIS PROPERTY - DEFAULT SCHEMA IS PUBLIC, but we are using a custom schema
                default_schema: ${DB_NAME}
    security:
        oauth2:
            client:
                registration:
                    keycloak:
                        client-id: backend
                        client-secret: HVeUzGBKo8DVKhREd8uYvF0ECd9ijO41
                        authorization-grant-type: authorization_code
                        redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
                        scope: openid, profile
                provider:
                    keycloak:
                        issuer-uri: http://localhost:8888/realms/candido-realm-dev
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8888/realms/candido-realm-dev

management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
    metrics:
        enable:
            all: true
            hibernate: true
            jdbc: true
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                all: true
            percentiles:
                all: [ 0.5, 0.75, 0.95, 0.99 ]



application:
    name: candido
    client:
        domain: http://localhost:3000
    security:
        jwt:
            issuer: Candido
            expiration: 86400000 # 1 day in ms
            refresh-token:
                expiration: 604800000 # 7 days in ms
            registration-token:
                expiration: 864000000 # 10 days in ms
            reset-token:
                expiration: 864000000 # 10 days in ms
    email:
        host: ${SMTP_HOST}
        port: 587
        username: apikey
        password: ${SMTP_PASSWORD}
        protocol: smtp
        smtp:
            auth: true
            starttls:
                enable: true
        debug: false
        no-reply: ${SMTP_NO_REPLY}
        can-send: ${SMTP_CAN_SEND}
    support:
        phone: 1234567890
        email: support@candido.com
    api:
        version: 0.0.1
        description: API for managing the entire online application project.
        server:
            development:
                url: http://localhost:8080/
            production:
                url: http://candido.com:8080/
    tos:
        uri: http://localhost:8080/terms-of-service